BEGIN TRANSACTION;

BEGIN TRY
	IF OBJECT_ID('dbo.Klant', 'U') IS NOT NULL
	BEGIN
		DROP TABLE dbo.Klant
	END

	CREATE TABLE [dbo].[Klant]
	(
		[id] INT NOT NULL PRIMARY KEY IDENTITY,
		[naam] NVARCHAR(255) NOT NULL,
		[adres] NVARCHAR(255) NOT NULL,
	)

	COMMIT
END TRY
BEGIN CATCH
	ROLLBACK;
END CATCH;